index:
    path: /
    controller: App\Controller\Homepage::__invoke()

api_login_check:
    path: /api/login_check

api_sign_in:
    path: /sign-in
    methods: ['POST']

api_sign_out:
    path: /sign-out
    methods: ['GET']